module Sim.Builtin.Stack
   ( stackFile
   ) where

import Data.Text

stackFile :: Text
stackFile = pack
   "# This file was automatically generated by 'stack init'\n\
   \#\n\
   \# Some commonly used options have been documented as comments in this file.\n\
   \# For advanced use and comprehensive documentation of the format, please see:\n\
   \# https://docs.haskellstack.org/en/stable/yaml_configuration/\n\
   \\n\
   \# Resolver to choose a 'specific' stackage snapshot or a compiler version.\n\
   \# A snapshot resolver dictates the compiler version and the set of packages\n\
   \# to be used for project dependencies. For example:\n\
   \#\n\
   \# resolver: lts-3.5\n\
   \# resolver: nightly-2015-09-21\n\
   \# resolver: ghc-7.10.2\n\
   \# resolver: ghcjs-0.1.0_ghc-7.10.2\n\
   \# resolver:\n\
   \#  name: custom-snapshot\n\
   \#  location: \"./custom-snapshot.yaml\"\n\
   \resolver: lts-9.10\n\
   \\n\
   \# User packages to be built.\n\
   \# Various formats can be used as shown in the example below.\n\
   \#\n\
   \# packages:\n\
   \# - some-directory\n\
   \# - https://example.com/foo/bar/baz-0.0.2.tar.gz\n\
   \# - location:\n\
   \#    git: https://github.com/commercialhaskell/stack.git\n\
   \#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a\n\
   \# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a\n\
   \#   extra-dep: true\n\
   \#  subdirs:\n\
   \#  - auto-update\n\
   \#  - wai\n\
   \#\n\
   \# A package marked 'extra-dep: true' will only be built if demanded by a\n\
   \# non-dependency (i.e. a user package), and its test suites and benchmarks\n\
   \# will not be run. This is useful for tweaking upstream packages.\n\
   \packages:\n\
   \- .\n\
   \# Dependency packages to be pulled from upstream that are not in the resolver\n\
   \# (e.g., acme-missiles-0.3)\n\
   \extra-deps: []\n\
   \#- mtl-2.2.2\n\
   \\n\
   \# Override default flag values for local packages and extra-deps\n\
   \flags: {}\n\
   \\n\
   \# Extra package databases containing global packages\n\
   \extra-package-dbs: []\n\
   \\n\
   \# Control whether we use the GHC we find on the path\n\
   \# system-ghc: true\n\
   \#\n\
   \# Require a specific version of stack, using version ranges\n\
   \# require-stack-version: -any # Default\n\
   \# require-stack-version: \">=1.5\"\n\
   \#\n\
   \# Override the architecture used by stack, especially useful on Windows\n\
   \# arch: i386\n\
   \# arch: x86_64\n\
   \#\n\
   \# Extra directories used by stack for building\n\
   \# extra-include-dirs: [/path/to/dir]\n\
   \# extra-lib-dirs: [/path/to/dir]\n\
   \#\n\
   \# Allow a newer minor version of GHC than the snapshot specifies\n\
   \# compiler-check: newer-minor"
